{
  "formatVersion": "1.1",
  "component": {
    "group": "com.nixsensor",
    "module": "universalsdk",
    "version": "4.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "universalsdk-4.1.0.aar",
          "url": "universalsdk-4.1.0.aar",
          "size": 846750,
          "sha512": "adf72a643ac04a406c3057051991652ec8e9a1667ea687da3e10cc5b37e73d1b9f279b22be915c9ac12da28b4b0f600ffb7684203770f13f408fc94f2a61fe90",
          "sha256": "47f144ea5e75c6d40555c65152724a5ce1548b37b16508678d98f795394c2291",
          "sha1": "ff53fca20dacf2efbb1af2ecbd6cdefb99af1888",
          "md5": "4f5001b3cd22924ac14b4b7aac932df2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment",
          "version": {
            "requires": "1.5.5"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "com.github.mik3y",
          "module": "usb-serial-for-android",
          "version": {
            "requires": "v3.4.6"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-analytics",
          "version": {
            "requires": "18.0.2"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.9"
          }
        }
      ],
      "files": [
        {
          "name": "universalsdk-4.1.0.aar",
          "url": "universalsdk-4.1.0.aar",
          "size": 846750,
          "sha512": "adf72a643ac04a406c3057051991652ec8e9a1667ea687da3e10cc5b37e73d1b9f279b22be915c9ac12da28b4b0f600ffb7684203770f13f408fc94f2a61fe90",
          "sha256": "47f144ea5e75c6d40555c65152724a5ce1548b37b16508678d98f795394c2291",
          "sha1": "ff53fca20dacf2efbb1af2ecbd6cdefb99af1888",
          "md5": "4f5001b3cd22924ac14b4b7aac932df2"
        }
      ]
    }
  ]
}
